### ISSUE TITLE
Limitar conexión de clientes y servidores por versión

### ISSUE THREAD

**Issue by luksdlt92** [ao-libre/finisterra#221]
**Descripción:** para evitar problemas de consistencia, hay que limitar el uso de ciertas versiones del cliente a ciertas versiones del servidor. De esta forma, no habría requests y responses que no sepan interpretar uno u otro.

**Comment by jopiortiz** [comment]
Agregar una propiedad en el Server.json con el numero de la version de esta forma:

````version: 0.11.2-FECHA_DE_COMPILACION```
