### ISSUE TITLE
Relación de aspecto fija

### ISSUE THREAD

**Issue by cpbeto** [ao-libre/finisterra#266]
Podríamos usar una relación de aspecto predeterminada, por ej. 800x600 o algo así, que se ajuste al tamaño de la ventana.

Así es ahora:
![image](https://user-images.githubusercontent.com/41555339/70855590-1d1efe00-1eac-11ea-9801-302c3e8457c9.png)
![image](https://user-images.githubusercontent.com/41555339/70855601-52c3e700-1eac-11ea-9a4c-84627d6bfc67.png)
![image](https://user-images.githubusercontent.com/41555339/70855607-696a3e00-1eac-11ea-8638-6478cb63e00d.png)

Usando _FitViewport_ de libGDX quedaría algo así:
![image](https://user-images.githubusercontent.com/41555339/70855624-c82fb780-1eac-11ea-8a9a-dc3940ea9f3e.png)

Quedan las barras negras como cuando se abre un juego de 800x600 en una pantalla de resolución mayor. De esta manera no se deforman los gráficos con los diferentes tamaños de ventana, se escalan proporcionalmente.

**Comment by jopiortiz** [comment]
Ya hay una manera de fijar el tamaño de la ventana del juego.

Fijate en el Config.json que hay una propiedad llamada `Resizeable` donde podes habilitar o no el cambio de tamaño de la ventana del juego. Si la dejas en `false` queda fija en la resulucion establecida en el mismo archivo (ver `width` y `height`)

**Comment by guidota** [comment]
Creo que a lo que se refiere beto, es no permitir nunca que se haga un resize a dimensiones que no tengan el mismo aspecto que 800x600
Me parece bien el planteo, habria que ver como manejar el tema de la full screen y aspecto de la pantalla del usuario.
Banco que hay que hacer algo a respecto 👍
