### ISSUE TITLE
UserSystem Guardado de personajes

### ISSUE THREAD

**Issue by Derillo** [ao-libre/finisterra#333]
El problema de la serializacion se esta dando en el momento que tiene que volver a leer archivo json guardado. Al parecer tenemos 3 usos de json, json de libgdx de artemis y nuestro propio AoJson. En la linea que se produce el error es: 

**Edit:** En un momento, me cambio el nombre del personaje y guardo un archivo nuevo en decimal. Luego al entrar con el personaje, accede al archivo que duplico en vez de al original. A partir de acá, duplica todos los archivos y crea un .0. Al reiniciar el cliente deja de pasar

**Branch savePJ-json-charfile**

- **Usando Cuenta antigua**
- [x] Loguear un personaje del sistema de cuentas anterior devuelve el error, no se pudo leer el personaje, contacte a un administrador
- [x] Es posible crear un nuevo personaje en una cuenta antigua.
- [x] Es posible crear un personaje en una cuenta antigua
- [x] Intentar volver a reingresar con un personaje creado. Reescribe el json con solo este contenido `{"components":[]}`
- [x] Guardado satisfactorio al realizar cambios en el personaje

- **Usando una cuenta nueva**
- [x] Crear una cuenta
- [x] Crear un personaje - Primer loguin
- [x] Reingresar con una cuenta nueva: No es posible, Error al loguearse en `LoguinScreen `
- [x] Reingresar con el personaje
- [x] Guardar cambios en el personaje

***Branch master**
- [x]  Agregar al crear guardar inmediatamente el char .json (actualmente no se guarda)
**Solved** Faltaba una llamada en `UserSystem.Create`
- [x] Usar la clase correcta json
- [x] Resolver: Los personajes no se guardan 
- [x] Revisar el uso `EntityJsonSerializer` para guardar

![imagen](https://user-images.githubusercontent.com/15325019/80274905-3b93d200-86b4-11ea-8be0-a4e5a1c573d3.png)
![imagen](https://user-images.githubusercontent.com/15325019/80275013-f7550180-86b4-11ea-84bd-2440d1ba798e.png)
![imagen](https://user-images.githubusercontent.com/15325019/80275028-0936a480-86b5-11ea-9196-a8ebf959ad98.png)
![imagen](https://user-images.githubusercontent.com/15325019/80275198-11431400-86b6-11ea-9f1c-dee3ce128535.png)

**Comment by jopiortiz** [comment]
Se revisó y arregló todo.
