### ISSUE TITLE
How i can edit the UI? Como puedo editar alguna interfaz como por ejemplo el login 

### ISSUE THREAD

**Issue by SEBASIAO** [ao-libre/finisterra#369]

**Comment by cpbeto** [comment]
Hola 👋🏻 

Fijate que en [esta carpeta](https://github.com/ao-libre/finisterra/tree/master/client/src/game/screens) están todas las pantallas de juego, incluida [LoginScreen](https://github.com/ao-libre/finisterra/blob/master/client/src/game/screens/LoginScreen.java), que es la pantalla de logueo.

En el método `createUI` se crea la interfaz programáticamente. Ahí tendrías que meter mano.

Si querés más detalle de cómo funciona, te recomiendo leer la documentación de libGDX sobre [Scene2d.ui](https://github.com/libgdx/libgdx/wiki/Scene2d.ui), que es lo que se usa para armar las interfaces.

Ahora bien, la parte gráfica (i.e. las imágenes de fondo, de botones, marcos, etc.) se compila todo en un [skin](https://github.com/libgdx/libgdx/wiki/Skin) de libGDX.

Entonces, una interfaz tiene una **parte programática** de maquetado (como si fuese HTML) y otra **parte gráfica** donde se le asigna a cada componente las imagenes que necesite para dibujarse (una barra de desplazamiento, por ejemplo, tiene una imagen de fondo y el deslizador); esta segunda parte se resuelve automáticamente pasando la skin como parámetro al crear un componente.

Hay una herramienta que se menciona en la wiki, [Skin Composer](https://ray3k.wordpress.com/software/skin-composer-for-libgdx/), la podés usar para editar una skin.

Si querés, podés pasar por el discord para que te sigamos ayudando.

Saludos 👍🏻

**Comment by SEBASIAO** [comment]
Sii, el link del discord está fallando, soy desarrollador Android jr y super fan del argentum, hace mucho tiempo quise hacer el mio en java pero lo abandoné y me encuentro esto que está super avanzado y me gustaria aprender y si puedo colaborar :D @cpbeto

**Comment by cpbeto** [comment]
Probá [este nuevo link](https://discord.gg/4Wd4EMwnFm). Estamos en la categoría que se llama `Finisterra - Java 15`.

**Comment by cpbeto** [comment]
Genial @SEBASIAO , hay muchas cosas que podés hacer en el proyecto. En el discord seguimos hablando. 👍🏻
