### ISSUE TITLE
Implement in-game command parser.

### ISSUE THREAD

**Issue by jopiortiz** [ao-libre/finisterra#94]

**Comment by guidota** [comment]
Como seria esto?

**Comment by jopiortiz** [comment]
Como en el AO de VB6... Apretas ENTER y escribis "/MEDITAR" y meditas.

Basicamente, hacer que el InputBox interprete el string con `/` adelante como un comando.

**Comment by Derillo** [comment]
Vote: No include in MVP

**Comment by cpbeto** [comment]
Resuelto en #303.
